// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHyekUOBctKfdSYgMcsMiuetoGFugyNU',
    appId: '1:143136098291:web:16103c165af2368bb63486',
    messagingSenderId: '143136098291',
    projectId: 'aphora-b2392',
    authDomain: 'aphora-b2392.firebaseapp.com',
    storageBucket: 'aphora-b2392.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6dkOpI0VtzuAsDoLumRrK7_kfEoRxug',
    appId: '1:143136098291:android:4e093b6b9cf36087b63486',
    messagingSenderId: '143136098291',
    projectId: 'aphora-b2392',
    storageBucket: 'aphora-b2392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1a4nvo_YbpuCB264T8w6Q9af7M5CQmUM',
    appId: '1:143136098291:ios:c3610836992136cab63486',
    messagingSenderId: '143136098291',
    projectId: 'aphora-b2392',
    storageBucket: 'aphora-b2392.firebasestorage.app',
    iosBundleId: 'com.example.aphora',
  );
}
